language: ruby
rvm:
- 2.6.0
bundler_args: --jobs=2
before_script:
  - psql -c 'create database whatidid_test;' -U postgres
script:
script:
  - bundle exec rake db:setup
  - bundle exec rake spec
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.4"